services:
  system:
    container_name: chat-nestjs
    build:
      context: ./
      dockerfile: ./Dockerfile
    # 定义该服务所依赖的其他服务，它们将按照依赖顺序启动
    depends_on:
      - mysql-container
    # 定义环境变量
    environment:
      - NODE_ENV=prod
    restart: on-failure
    ports:
      - '3000:3000'
    networks:
      - common-network

    # 定义一个名为'mysql-container'的服务，使用mysql镜像
  mysql-container:
    container_name: mysql-container
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    # 数据卷配置，用于持久化数据
    volumes:
      - /home/server_volumes/mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: chat_system
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
    networks:
      - common-network

# 网络配置
networks:
  common-network:
    driver: bridge
